# Generated by Django 4.0a1 on 2021-10-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_login_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Select Gender', 'Select Gender'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Select Gender', max_length=20),
        ),
    ]
