# Generated by Django 4.0a1 on 2021-10-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_bookedday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedday',
            name='created',
        ),
        migrations.RemoveField(
            model_name='bookedday',
            name='updated',
        ),
    ]
