# Generated by Django 4.0a1 on 2021-10-19 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_avatar_alter_user_bio_and_more'),
        ('lists', '0002_auto_20210903_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='users.user'),
        ),
    ]
